# Generated by Django 3.2.4 on 2021-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phnum',
            field=models.CharField(max_length=12),
        ),
    ]
